// src/constants/AppTextStyles.ts
import { StyleSheet, TextStyle } from 'react-native';

// import { Dimensions } from 'react-native';

// const { width } = Dimensions.get('window');

// // Example scaling function
// const scale = (size: number) => (width / 375) * size; 

const defaultFontFamily = 'SpaceMono';

export const AppTextStyles = StyleSheet.create({
  font56Weight500: {
    fontSize: 56,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  } as TextStyle,
  font40Weight600: {
    fontSize: 40,
    fontWeight: '600',
    fontFamily: defaultFontFamily,
  } as TextStyle,
  font40Weight500: {
    fontSize: 40,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  } as TextStyle,
  font24Weight800: {
    fontSize: 24,
    fontWeight: '800',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font24: {
    fontSize: 24,
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font24Weight500: {
    fontSize: 24,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font24Weight700: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font20: {
    fontSize: 20,
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font20Weight500: {
    fontSize: 20,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font20Weight600: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font20Weight700: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font20Weight800: {
    fontSize: 20,
    fontWeight: '800',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font18: {
    fontSize: 18,
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font18Weight600: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font18Weight700: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font18Weight500: {
    fontSize: 18,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font17Weight500: {
    fontSize: 17,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font16: {
    fontSize: 16,
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font16Weight500: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font16Weight700: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font16Weight800: {
    fontSize: 16,
    fontWeight: '800',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font16Weight600: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font15Weight500: {
    fontSize: 15,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font14: {
    fontSize: 14,
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font14Weight500: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font14Weight600: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font14Weight700: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font14Weight800: {
    fontSize: 14,
    fontWeight: '800',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font13Weight500: {
    fontSize: 13,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font13: {
    fontSize: 13,
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font12: {
    fontSize: 12,
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font12Weight500: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font12Weight600: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font12Weight700: {
    fontSize: 12,
    fontWeight: '700',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font10Weight600: {
    fontSize: 10,
    fontWeight: '600',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font10Weight500: {
    fontSize: 10,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  }as TextStyle,
  font9Weight500: {
    fontSize: 9,
    fontWeight: '500',
    fontFamily: defaultFontFamily,
  },
});

